name: Run Python Script

on:
  workflow_dispatch:
  #push:
  #  branches: [master]
  #pull_request:
  #  branches: [master]
  
jobs:
  setup-codeql:
    runs-on: ubuntu-latest
    timeout-minutes: 12000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Set up Git
        run: |
          git config --global user.email "arpitjain799@gmail.com"
          git config --global user.name "Arpit Jain"

      - name: Run Python script with secret
        run: |
          python forkrepo.py
